/** ISO country code → English short name (subset + fallback). */
const COUNTRY_NAMES: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BR: 'Brazil',
  CA: 'Canada',
  CH: 'Switzerland',
  CL: 'Chile',
  CN: 'China',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  ES: 'Spain',
  FI: 'Finland',
  FR: 'France',
  GB: 'United Kingdom',
  GR: 'Greece',
  HK: 'Hong Kong',
  HR: 'Croatia',
  HU: 'Hungary',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IT: 'Italy',
  JP: 'Japan',
  KR: 'South Korea',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MX: 'Mexico',
  NL: 'Netherlands',
  NO: 'Norway',
  NZ: 'New Zealand',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  TR: 'Turkey',
  TW: 'Taiwan',
  UA: 'Ukraine',
  US: 'United States',
  ZA: 'South Africa',
  ZZ: 'Unknown',
}

/** Rough lon/lat centroids for a privacy-safe country-level map (not precise location). */
const COUNTRY_CENTROIDS: Record<string, [number, number]> = {
  AD: [1.5, 42.5],
  AE: [54, 24],
  AR: [-64, -34],
  AT: [14.5, 47.5],
  AU: [133, -27],
  BE: [4.5, 50.5],
  BG: [25, 43],
  BR: [-52, -14],
  CA: [-96, 60],
  CH: [8, 47],
  CL: [-71, -35],
  CN: [105, 35],
  CZ: [15.5, 50],
  DE: [10, 51],
  DK: [10, 56],
  EE: [26, 59],
  ES: [-3, 40],
  FI: [26, 64],
  FR: [2, 46],
  GB: [-2, 54],
  GR: [22, 39],
  HK: [114, 22],
  HR: [16, 45],
  HU: [19, 47],
  IE: [-8, 53],
  IL: [35, 31],
  IN: [78, 22],
  IT: [12.5, 42],
  JP: [138, 36],
  KR: [128, 36],
  LT: [24, 55],
  LU: [6, 50],
  LV: [25, 57],
  MX: [-102, 23],
  NL: [5.5, 52],
  NO: [9, 62],
  NZ: [174, -41],
  PL: [19, 52],
  PT: [-8, 40],
  RO: [25, 46],
  RS: [21, 44],
  RU: [100, 60],
  SE: [15, 62],
  SG: [104, 1],
  SI: [14.5, 46],
  SK: [19.5, 49],
  TR: [35, 39],
  TW: [121, 24],
  UA: [32, 49],
  US: [-98, 39],
  ZA: [25, -29],
}

export function countryName(code: string): string {
  const normalized = code.toUpperCase()
  return COUNTRY_NAMES[normalized] ?? normalized
}

export function countryCentroid(code: string): [number, number] | null {
  return COUNTRY_CENTROIDS[code.toUpperCase()] ?? null
}

export function projectLonLat(
  lon: number,
  lat: number,
  width: number,
  height: number,
): { x: number; y: number } {
  const x = ((lon + 180) / 360) * width
  const y = ((90 - lat) / 180) * height
  return { x, y }
}
